package com.devskill.devskill_api.services;

import com.devskill.devskill_api.models.Extension;
import com.devskill.devskill_api.models.ExtensionDTO;
import com.devskill.devskill_api.models.RepositoryEntity;
import com.devskill.devskill_api.repository.ExtensionRepository;
import com.devskill.devskill_api.utils.Utils;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.*;

@Service
public class ExtensionService {

    @Autowired
    private ExtensionRepository extensionRepository;

    @Autowired
    private Utils utils;

    private final Map<String, List<String>> extensionToLanguages = new HashMap<>();

    @PostConstruct
    public void init() {
        initializeMappings();
    }


    public Map<String, Object> getExtensions(Pageable pageable) {
        Page<ExtensionDTO> extensions = extensionRepository.findAll(pageable)
                .map(s -> new ExtensionDTO(
                        s.getExtensionName(),
                        s.getLanguage(),
                        s.getFileCount(),
                        s.getRepoCount(),
                        s.getLastUsed()
                ));

        return utils.constructPageResponse(extensions);
    }

    public Map<String, Object> getFilteredExtensions(String extensionName, Pageable pageable) {
        Page<ExtensionDTO> extensions =  extensionRepository.findByExtensionName(extensionName, pageable)
                .map(s -> new ExtensionDTO(
                        s.getExtensionName(),
                        s.getLanguage(),
                        s.getFileCount(),
                        s.getRepoCount(),
                        s.getLastUsed()
                ));

        return utils.constructPageResponse(extensions);
    }

    public void updateExtensionTable(boolean repoExist, Map<String, Integer> extensionCounts, LocalDate lastCommitDate) {
        for (Map.Entry<String, Integer> entry : extensionCounts.entrySet()) {
            String extensionName = entry.getKey();
            int fileCount = entry.getValue();

            // Find or create extension entity
            Optional<Extension> optionalExtension = extensionRepository.findById(extensionName);
            Extension extension;

            if (optionalExtension.isPresent()) {
                // Extension exists, update file_count and last_used
                extension = optionalExtension.get();
                if(!repoExist){
                    extension.setRepoCount(extension.getRepoCount() + 1);
                }
                extension.setFileCount(extension.getFileCount() + fileCount);
                LocalDate newLastUsed = extension.getLastUsed() != null && lastCommitDate != null ?
                        (lastCommitDate.isAfter(extension.getLastUsed()) ? lastCommitDate : extension.getLastUsed()) :
                        lastCommitDate;
                extension.setLastUsed(newLastUsed);
            } else {
                // Extension does not exist, create new with repo_count=1
                System.out.println(extensionName);
                extension = new Extension(extensionName , extensionToLanguages.get(extensionName) != null? extensionToLanguages.get(extensionName) : List.of("other") , 1, fileCount, lastCommitDate);
            }


            extensionRepository.save(extension);
        }
    }

    private void initializeMappings() {
        // Hardcoded extension-to-language mappings from languages.yml
        extensionToLanguages.put("bsl", Arrays.asList("1C Enterprise"));
        extensionToLanguages.put("os", Arrays.asList("1C Enterprise"));
        extensionToLanguages.put("abap", Arrays.asList("ABAP"));
        extensionToLanguages.put("abnf", Arrays.asList("ABNF"));
        extensionToLanguages.put("as", Arrays.asList("ActionScript", "AngelScript"));
        extensionToLanguages.put("asc", Arrays.asList("AGS Script", "AsciiDoc"));
        extensionToLanguages.put("ash", Arrays.asList("AGS Script"));
        extensionToLanguages.put("aidl", Arrays.asList("AIDL"));
        extensionToLanguages.put("al", Arrays.asList("AL"));
        extensionToLanguages.put("ampl", Arrays.asList("AMPL"));
        extensionToLanguages.put("mod", Arrays.asList("AMPL", "XML"));
        extensionToLanguages.put("g4", Arrays.asList("ANTLR"));
        extensionToLanguages.put("apib", Arrays.asList("API Blueprint"));
        extensionToLanguages.put("apl", Arrays.asList("APL"));
        extensionToLanguages.put("dyalog", Arrays.asList("APL"));
        extensionToLanguages.put("asp", Arrays.asList("Classic ASP"));
        extensionToLanguages.put("asax", Arrays.asList("ASP.NET"));
        extensionToLanguages.put("ascx", Arrays.asList("ASP.NET"));
        extensionToLanguages.put("ashx", Arrays.asList("ASP.NET"));
        extensionToLanguages.put("asmx", Arrays.asList("ASP.NET"));
        extensionToLanguages.put("aspx", Arrays.asList("ASP.NET"));
        extensionToLanguages.put("axd", Arrays.asList("ASP.NET"));
        extensionToLanguages.put("adoc", Arrays.asList("AsciiDoc"));
        extensionToLanguages.put("asciidoc", Arrays.asList("AsciiDoc"));
        extensionToLanguages.put("asm", Arrays.asList("Assembly"));
        extensionToLanguages.put("a51", Arrays.asList("Assembly"));
        extensionToLanguages.put("inc", Arrays.asList("Assembly", "C++", "SourcePawn"));
        extensionToLanguages.put("nasm", Arrays.asList("Assembly"));
        extensionToLanguages.put("s", Arrays.asList("Assembly", "Unix Assembly"));
        extensionToLanguages.put("ms", Arrays.asList("Unix Assembly"));
        extensionToLanguages.put("agc", Arrays.asList("Apollo Guidance Computer"));
        extensionToLanguages.put("astro", Arrays.asList("Astro"));
        extensionToLanguages.put("asy", Arrays.asList("Asymptote"));
        extensionToLanguages.put("aug", Arrays.asList("Augeas"));
        extensionToLanguages.put("ahk", Arrays.asList("AutoHotkey"));
        extensionToLanguages.put("ahkl", Arrays.asList("AutoHotkey"));
        extensionToLanguages.put("au3", Arrays.asList("AutoIt"));
        extensionToLanguages.put("awk", Arrays.asList("Awk"));
        extensionToLanguages.put("auk", Arrays.asList("Awk"));
        extensionToLanguages.put("gawk", Arrays.asList("Awk"));
        extensionToLanguages.put("mawk", Arrays.asList("Awk"));
        extensionToLanguages.put("nw", Arrays.asList("Awk"));
        extensionToLanguages.put("b", Arrays.asList("Brainfuck"));
        extensionToLanguages.put("bf", Arrays.asList("Beef", "Befunge", "Brainfuck"));
        extensionToLanguages.put("bal", Arrays.asList("Ballerina"));
        extensionToLanguages.put("bas", Arrays.asList("B4X", "BASIC", "Visual Basic 6.0"));
        extensionToLanguages.put("cls", Arrays.asList("Apex", "VBA", "Visual Basic 6.0"));
        extensionToLanguages.put("frm", Arrays.asList("Visual Basic 6.0"));
        extensionToLanguages.put("bat", Arrays.asList("Batchfile"));
        extensionToLanguages.put("cmd", Arrays.asList("Batchfile"));
        extensionToLanguages.put("bats", Arrays.asList("Shell"));
        extensionToLanguages.put("bb", Arrays.asList("BitBake", "BlitzBasic", "Clojure"));
        extensionToLanguages.put("befunge", Arrays.asList("Befunge"));
        extensionToLanguages.put("bib", Arrays.asList("BibTeX"));
        extensionToLanguages.put("bst", Arrays.asList("BibTeX Style"));
        extensionToLanguages.put("bicep", Arrays.asList("Bicep"));
        extensionToLanguages.put("bbx", Arrays.asList("TeX"));
        extensionToLanguages.put("cbx", Arrays.asList("TeX"));
        extensionToLanguages.put("cl", Arrays.asList("Common Lisp", "Cool", "OpenCL"));
        extensionToLanguages.put("lisp", Arrays.asList("Common Lisp", "NewLisp"));
        extensionToLanguages.put("lsp", Arrays.asList("Common Lisp", "NewLisp"));
        extensionToLanguages.put("c", Arrays.asList("C"));
        extensionToLanguages.put("h", Arrays.asList("C", "C++"));
        extensionToLanguages.put("cats", Arrays.asList("C"));
        extensionToLanguages.put("idc", Arrays.asList("C"));
        extensionToLanguages.put("w", Arrays.asList("C"));
        extensionToLanguages.put("cake", Arrays.asList("C#"));
        extensionToLanguages.put("cs", Arrays.asList("C#", "Smalltalk"));
        extensionToLanguages.put("csx", Arrays.asList("C#"));
        extensionToLanguages.put("linq", Arrays.asList("C#"));
        extensionToLanguages.put("cpp", Arrays.asList("C++"));
        extensionToLanguages.put("c++", Arrays.asList("C++"));
        extensionToLanguages.put("cc", Arrays.asList("C++"));
        extensionToLanguages.put("cp", Arrays.asList("C++", "Component Pascal"));
        extensionToLanguages.put("cxx", Arrays.asList("C++"));
        extensionToLanguages.put("hh", Arrays.asList("C++"));
        extensionToLanguages.put("hpp", Arrays.asList("C++"));
        extensionToLanguages.put("hxx", Arrays.asList("C++"));
        extensionToLanguages.put("inl", Arrays.asList("C++"));
        extensionToLanguages.put("ipp", Arrays.asList("C++"));
        extensionToLanguages.put("re", Arrays.asList("C++"));
        extensionToLanguages.put("tcc", Arrays.asList("C++"));
        extensionToLanguages.put("tpp", Arrays.asList("C++"));
        extensionToLanguages.put("capnp", Arrays.asList("Cap'n Proto"));
        extensionToLanguages.put("cds", Arrays.asList("CAP CDS"));
        extensionToLanguages.put("ceylon", Arrays.asList("Ceylon"));
        extensionToLanguages.put("ch", Arrays.asList("Charity", "xBase"));
        extensionToLanguages.put("cbl", Arrays.asList("COBOL"));
        extensionToLanguages.put("cob", Arrays.asList("COBOL"));
        extensionToLanguages.put("cpy", Arrays.asList("COBOL"));
        extensionToLanguages.put("cdc", Arrays.asList("Cairo"));
        extensionToLanguages.put("cabal", Arrays.asList("Cabal Config"));
        extensionToLanguages.put("clj", Arrays.asList("Clojure"));
        extensionToLanguages.put("cljc", Arrays.asList("Clojure"));
        extensionToLanguages.put("cljs", Arrays.asList("Clojure"));
        extensionToLanguages.put("clp", Arrays.asList("CLIPS"));
        extensionToLanguages.put("cmake", Arrays.asList("CMake"));
        extensionToLanguages.put("cmake.in", Arrays.asList("CMake"));
        extensionToLanguages.put("cobol", Arrays.asList("COBOL"));
        extensionToLanguages.put("coffee", Arrays.asList("CoffeeScript"));
        extensionToLanguages.put("_coffee", Arrays.asList("CoffeeScript"));
        extensionToLanguages.put("cson", Arrays.asList("CSON"));
        extensionToLanguages.put("conllu", Arrays.asList("CoNLL-U"));
        extensionToLanguages.put("cr", Arrays.asList("Crystal"));
        extensionToLanguages.put("creole", Arrays.asList("Creole"));
        extensionToLanguages.put("csd", Arrays.asList("Csound Document"));
        extensionToLanguages.put("css", Arrays.asList("CSS"));
        extensionToLanguages.put("csv", Arrays.asList("CSV"));
        extensionToLanguages.put("cue", Arrays.asList("CUE"));
        extensionToLanguages.put("cuh", Arrays.asList("Cuda"));
        extensionToLanguages.put("cu", Arrays.asList("Cuda"));
        extensionToLanguages.put("cwl", Arrays.asList("Common Workflow Language"));
        extensionToLanguages.put("cylc", Arrays.asList("Cylc"));
        extensionToLanguages.put("cyp", Arrays.asList("Cypher"));
        extensionToLanguages.put("d", Arrays.asList("D"));
        extensionToLanguages.put("di", Arrays.asList("D"));
        extensionToLanguages.put("dart", Arrays.asList("Dart"));
        extensionToLanguages.put("dats", Arrays.asList("ATS"));
        extensionToLanguages.put("sats", Arrays.asList("ATS"));
        extensionToLanguages.put("hats", Arrays.asList("ATS"));
        extensionToLanguages.put("dfy", Arrays.asList("Dafny"));
        extensionToLanguages.put("dwl", Arrays.asList("DataWeave"));
        extensionToLanguages.put("dhall", Arrays.asList("Dhall"));
        extensionToLanguages.put("diff", Arrays.asList("Diff"));
        extensionToLanguages.put("patch", Arrays.asList("Diff"));
        extensionToLanguages.put("djs", Arrays.asList("Dogescript"));
        extensionToLanguages.put("dm", Arrays.asList("DM"));
        extensionToLanguages.put("dockerfile", Arrays.asList("Dockerfile"));
        extensionToLanguages.put("dsc", Arrays.asList("Debian Package Control File", "DenizenScript"));
        extensionToLanguages.put("dylan", Arrays.asList("Dylan"));
        extensionToLanguages.put("dyl", Arrays.asList("Dylan"));
        extensionToLanguages.put("intr", Arrays.asList("Dylan"));
        extensionToLanguages.put("lid", Arrays.asList("Dylan"));
        extensionToLanguages.put("e", Arrays.asList("E"));
        extensionToLanguages.put("eb", Arrays.asList("Easybuild"));
        extensionToLanguages.put("ebnf", Arrays.asList("EBNF"));
        extensionToLanguages.put("ec", Arrays.asList("eC"));
        extensionToLanguages.put("ecl", Arrays.asList("ECL", "ECLiPSe"));
        extensionToLanguages.put("eclxml", Arrays.asList("ECL"));
        extensionToLanguages.put("edc", Arrays.asList("Edje Data Collection"));
        extensionToLanguages.put("edn", Arrays.asList("edn"));
        extensionToLanguages.put("eex", Arrays.asList("Elixir"));
        extensionToLanguages.put("leex", Arrays.asList("Elixir"));
        extensionToLanguages.put("ex", Arrays.asList("Elixir"));
        extensionToLanguages.put("exs", Arrays.asList("Elixir"));
        extensionToLanguages.put("ejs", Arrays.asList("EJS"));
        extensionToLanguages.put("elm", Arrays.asList("Elm"));
        extensionToLanguages.put("el", Arrays.asList("Emacs Lisp"));
        extensionToLanguages.put("emacs", Arrays.asList("Emacs Lisp"));
        extensionToLanguages.put("emacs.desktop", Arrays.asList("Emacs Lisp"));
        extensionToLanguages.put("eml", Arrays.asList("E-mail"));
        extensionToLanguages.put("mbox", Arrays.asList("E-mail"));
        extensionToLanguages.put("eq", Arrays.asList("EQ"));
        extensionToLanguages.put("erl", Arrays.asList("Erlang"));
        extensionToLanguages.put("app.src", Arrays.asList("Erlang"));
        extensionToLanguages.put("es", Arrays.asList("Erlang"));
        extensionToLanguages.put("escript", Arrays.asList("Erlang"));
        extensionToLanguages.put("hrl", Arrays.asList("Erlang"));
        extensionToLanguages.put("xrl", Arrays.asList("Erlang"));
        extensionToLanguages.put("yrl", Arrays.asList("Erlang"));
        extensionToLanguages.put("fs", Arrays.asList("F#", "Filterscript", "Forth"));
        extensionToLanguages.put("fsi", Arrays.asList("F#"));
        extensionToLanguages.put("fsx", Arrays.asList("F#"));
        extensionToLanguages.put("fst", Arrays.asList("F*"));
        extensionToLanguages.put("f", Arrays.asList("Forth", "Fortran"));
        extensionToLanguages.put("factor", Arrays.asList("Factor"));
        extensionToLanguages.put("fy", Arrays.asList("Fancy"));
        extensionToLanguages.put("fancypack", Arrays.asList("Fancy"));
        extensionToLanguages.put("fan", Arrays.asList("Fantom"));
        extensionToLanguages.put("f90", Arrays.asList("Fortran"));
        extensionToLanguages.put("f03", Arrays.asList("Fortran"));
        extensionToLanguages.put("f08", Arrays.asList("Fortran"));
        extensionToLanguages.put("f77", Arrays.asList("Fortran"));
        extensionToLanguages.put("f95", Arrays.asList("Fortran"));
        extensionToLanguages.put("for", Arrays.asList("Fortran"));
        extensionToLanguages.put("fpp", Arrays.asList("Fortran"));
        extensionToLanguages.put("ftl", Arrays.asList("FreeMarker"));
        extensionToLanguages.put("fr", Arrays.asList("Text"));
        extensionToLanguages.put("txt", Arrays.asList("Text", "Adblock Filter List", "Vim Help File"));
        extensionToLanguages.put("fish", Arrays.asList("fish"));
        extensionToLanguages.put("flux", Arrays.asList("Flux"));
        extensionToLanguages.put("g", Arrays.asList("G-code"));
        extensionToLanguages.put("gco", Arrays.asList("G-code"));
        extensionToLanguages.put("gcode", Arrays.asList("G-code"));
        extensionToLanguages.put("gaml", Arrays.asList("GAML"));
        extensionToLanguages.put("gms", Arrays.asList("GAMS"));
        extensionToLanguages.put("gap", Arrays.asList("GAP"));
        extensionToLanguages.put("gd", Arrays.asList("GDScript"));
        extensionToLanguages.put("ged", Arrays.asList("GEDCOM"));
        extensionToLanguages.put("glsl", Arrays.asList("GLSL"));
        extensionToLanguages.put("fp", Arrays.asList("GLSL"));
        extensionToLanguages.put("fsh", Arrays.asList("GLSL"));
        extensionToLanguages.put("fshader", Arrays.asList("GLSL"));
        extensionToLanguages.put("gsh", Arrays.asList("GLSL"));
        extensionToLanguages.put("gshader", Arrays.asList("GLSL"));
        extensionToLanguages.put("vert", Arrays.asList("GLSL"));
        extensionToLanguages.put("vrx", Arrays.asList("GLSL"));
        extensionToLanguages.put("vsh", Arrays.asList("GLSL"));
        extensionToLanguages.put("vshader", Arrays.asList("GLSL"));
        extensionToLanguages.put("gn", Arrays.asList("GN"));
        extensionToLanguages.put("gni", Arrays.asList("GN"));
        extensionToLanguages.put("go", Arrays.asList("Go"));
        extensionToLanguages.put("graphql", Arrays.asList("GraphQL"));
        extensionToLanguages.put("graphqls", Arrays.asList("GraphQL"));
        extensionToLanguages.put("groovy", Arrays.asList("Groovy"));
        extensionToLanguages.put("grt", Arrays.asList("Groovy"));
        extensionToLanguages.put("gtpl", Arrays.asList("Groovy"));
        extensionToLanguages.put("gvy", Arrays.asList("Groovy"));
        extensionToLanguages.put("hcl", Arrays.asList("HCL"));
        extensionToLanguages.put("tf", Arrays.asList("HCL"));
        extensionToLanguages.put("tfvars", Arrays.asList("HCL"));
        extensionToLanguages.put("hlsl", Arrays.asList("HLSL"));
        extensionToLanguages.put("cginc", Arrays.asList("HLSL"));
        extensionToLanguages.put("shader", Arrays.asList("HLSL"));
        extensionToLanguages.put("html", Arrays.asList("HTML"));
        extensionToLanguages.put("htm", Arrays.asList("HTML"));
        extensionToLanguages.put("html.hl", Arrays.asList("HTML"));
        extensionToLanguages.put("xhtml", Arrays.asList("HTML"));
        extensionToLanguages.put("hack", Arrays.asList("Hack"));
        extensionToLanguages.put("hhi", Arrays.asList("Hack"));
        extensionToLanguages.put("haml", Arrays.asList("Haml"));
        extensionToLanguages.put("handlebars", Arrays.asList("Handlebars"));
        extensionToLanguages.put("hbs", Arrays.asList("Handlebars"));
        extensionToLanguages.put("hs", Arrays.asList("Haskell"));
        extensionToLanguages.put("lhs", Arrays.asList("Haskell"));
        extensionToLanguages.put("hx", Arrays.asList("Haxe"));
        extensionToLanguages.put("hxsl", Arrays.asList("Haxe"));
        extensionToLanguages.put("hy", Arrays.asList("Hy"));
        extensionToLanguages.put("icl", Arrays.asList("Clean"));
        extensionToLanguages.put("dcl", Arrays.asList("Clean"));
        extensionToLanguages.put("idris", Arrays.asList("Idris"));
        extensionToLanguages.put("lidr", Arrays.asList("Idris"));
        extensionToLanguages.put("ni", Arrays.asList("Inform 7"));
        extensionToLanguages.put("i7x", Arrays.asList("Inform 7"));
        extensionToLanguages.put("ini", Arrays.asList("INI"));
        extensionToLanguages.put("cfg", Arrays.asList("INI"));
        extensionToLanguages.put("le", Arrays.asList("INI"));
        extensionToLanguages.put("prefs", Arrays.asList("INI"));
        extensionToLanguages.put("pro", Arrays.asList("INI", "Prolog"));
        extensionToLanguages.put("properties", Arrays.asList("INI"));
        extensionToLanguages.put("io", Arrays.asList("Io"));
        extensionToLanguages.put("ik", Arrays.asList("Ioke"));
        extensionToLanguages.put("j", Arrays.asList("Jasmin"));
        extensionToLanguages.put("java", Arrays.asList("Java"));
        extensionToLanguages.put("js", Arrays.asList("JavaScript"));
        extensionToLanguages.put("_js", Arrays.asList("JavaScript"));
        extensionToLanguages.put("bones", Arrays.asList("JavaScript"));
        extensionToLanguages.put("cjs", Arrays.asList("JavaScript"));
        extensionToLanguages.put("es6", Arrays.asList("JavaScript"));
        extensionToLanguages.put("jake", Arrays.asList("JavaScript"));
        extensionToLanguages.put("jsb", Arrays.asList("JavaScript"));
        extensionToLanguages.put("jscad", Arrays.asList("JavaScript"));
        extensionToLanguages.put("jsfl", Arrays.asList("JavaScript"));
        extensionToLanguages.put("jsm", Arrays.asList("JavaScript"));
        extensionToLanguages.put("jss", Arrays.asList("JavaScript"));
        extensionToLanguages.put("mjs", Arrays.asList("JavaScript"));
        extensionToLanguages.put("njs", Arrays.asList("JavaScript"));
        extensionToLanguages.put("pac", Arrays.asList("JavaScript"));
        extensionToLanguages.put("sjs", Arrays.asList("JavaScript"));
        extensionToLanguages.put("ssjs", Arrays.asList("JavaScript"));
        extensionToLanguages.put("xsjs", Arrays.asList("JavaScript"));
        extensionToLanguages.put("xsjslib", Arrays.asList("JavaScript"));
        extensionToLanguages.put("jsx", Arrays.asList("JavaScript"));
        extensionToLanguages.put("jl", Arrays.asList("Julia"));
        extensionToLanguages.put("jq", Arrays.asList("jq"));
        extensionToLanguages.put("kt", Arrays.asList("Kotlin"));
        extensionToLanguages.put("kts", Arrays.asList("Kotlin"));
        extensionToLanguages.put("krl", Arrays.asList("KRL"));
        extensionToLanguages.put("kv", Arrays.asList("kvlang"));
        extensionToLanguages.put("lean", Arrays.asList("Lean"));
        extensionToLanguages.put("hlean", Arrays.asList("Lean"));
        extensionToLanguages.put("less", Arrays.asList("Less"));
        extensionToLanguages.put("lex", Arrays.asList("Lex"));
        extensionToLanguages.put("lfe", Arrays.asList("LFE"));
        extensionToLanguages.put("ll", Arrays.asList("LLVM"));
        extensionToLanguages.put("lgt", Arrays.asList("Logtalk"));
        extensionToLanguages.put("logtalk", Arrays.asList("Logtalk"));
        extensionToLanguages.put("lol", Arrays.asList("LOLCODE"));
        extensionToLanguages.put("lookml", Arrays.asList("LookML"));
        extensionToLanguages.put("model.lkml", Arrays.asList("LookML"));
        extensionToLanguages.put("view.lkml", Arrays.asList("LookML"));
        extensionToLanguages.put("ls", Arrays.asList("LiveScript", "LoomScript"));
        extensionToLanguages.put("_ls", Arrays.asList("LiveScript"));
        extensionToLanguages.put("lua", Arrays.asList("Lua"));
        extensionToLanguages.put("fcgi", Arrays.asList("Lua", "Perl", "PHP", "Python", "Ruby"));
        extensionToLanguages.put("nse", Arrays.asList("Lua"));
        extensionToLanguages.put("p8", Arrays.asList("Lua"));
        extensionToLanguages.put("pd_lua", Arrays.asList("Lua"));
        extensionToLanguages.put("rbxs", Arrays.asList("Lua"));
        extensionToLanguages.put("rockspec", Arrays.asList("Lua"));
        extensionToLanguages.put("wlua", Arrays.asList("Lua"));
        extensionToLanguages.put("m", Arrays.asList("M", "MATLAB", "Objective-C"));
        extensionToLanguages.put("mac", Arrays.asList("Max"));
        extensionToLanguages.put("maxpat", Arrays.asList("Max"));
        extensionToLanguages.put("maxhelp", Arrays.asList("Max"));
        extensionToLanguages.put("maxproj", Arrays.asList("Max"));
        extensionToLanguages.put("mxt", Arrays.asList("Max"));
        extensionToLanguages.put("matlab", Arrays.asList("MATLAB"));
        extensionToLanguages.put("mcr", Arrays.asList("Alchemist"));
        extensionToLanguages.put("md", Arrays.asList("Markdown"));
        extensionToLanguages.put("markdown", Arrays.asList("Markdown"));
        extensionToLanguages.put("mdown", Arrays.asList("Markdown"));
        extensionToLanguages.put("mdwn", Arrays.asList("Markdown"));
        extensionToLanguages.put("mkd", Arrays.asList("Markdown"));
        extensionToLanguages.put("mkdn", Arrays.asList("Markdown"));
        extensionToLanguages.put("mkdown", Arrays.asList("Markdown"));
        extensionToLanguages.put("ronn", Arrays.asList("Markdown"));
        extensionToLanguages.put("mc", Arrays.asList("MCode"));
        extensionToLanguages.put("ml", Arrays.asList("OCaml"));
        extensionToLanguages.put("eliom", Arrays.asList("OCaml"));
        extensionToLanguages.put("eliomi", Arrays.asList("OCaml"));
        extensionToLanguages.put("ml4", Arrays.asList("OCaml"));
        extensionToLanguages.put("mli", Arrays.asList("OCaml"));
        extensionToLanguages.put("mll", Arrays.asList("OCaml"));
        extensionToLanguages.put("mly", Arrays.asList("OCaml"));
        extensionToLanguages.put("mo", Arrays.asList("Modelica"));
        extensionToLanguages.put("mms", Arrays.asList("Module Management System"));
        extensionToLanguages.put("mmk", Arrays.asList("Module Management System"));
        extensionToLanguages.put("monkey", Arrays.asList("Monkey"));
        extensionToLanguages.put("monkey2", Arrays.asList("Monkey X"));
        extensionToLanguages.put("moon", Arrays.asList("MoonScript"));
        extensionToLanguages.put("mu", Arrays.asList("mupad"));
        extensionToLanguages.put("mustache", Arrays.asList("Mustache"));
        extensionToLanguages.put("myt", Arrays.asList("Myghty"));
        extensionToLanguages.put("nas", Arrays.asList("Nasal"));
        extensionToLanguages.put("ncl", Arrays.asList("NCL"));
        extensionToLanguages.put("nl", Arrays.asList("NL"));
        extensionToLanguages.put("nsi", Arrays.asList("NSIS"));
        extensionToLanguages.put("nsh", Arrays.asList("NSIS"));
        extensionToLanguages.put("ne", Arrays.asList("Nearley"));
        extensionToLanguages.put("nearley", Arrays.asList("Nearley"));
        extensionToLanguages.put("n", Arrays.asList("Nemerle"));
        extensionToLanguages.put("axs", Arrays.asList("NetLinx"));
        extensionToLanguages.put("axi", Arrays.asList("NetLinx"));
        extensionToLanguages.put("axs.erb", Arrays.asList("NetLinx+ERB"));
        extensionToLanguages.put("axi.erb", Arrays.asList("NetLinx+ERB"));
        extensionToLanguages.put("nlogo", Arrays.asList("NetLogo"));
        extensionToLanguages.put("nf", Arrays.asList("Nextflow"));
        extensionToLanguages.put("nginx", Arrays.asList("Nginx"));
        extensionToLanguages.put("nginxconf", Arrays.asList("Nginx"));
        extensionToLanguages.put("nim", Arrays.asList("Nim"));
        extensionToLanguages.put("nimble", Arrays.asList("Nim"));
        extensionToLanguages.put("nimrod", Arrays.asList("Nim"));
        extensionToLanguages.put("nims", Arrays.asList("Nim"));
        extensionToLanguages.put("nit", Arrays.asList("Nit"));
        extensionToLanguages.put("nix", Arrays.asList("Nix"));
        extensionToLanguages.put("nu", Arrays.asList("Nu"));
        extensionToLanguages.put("numpy", Arrays.asList("NumPy"));
        extensionToLanguages.put("numpyw", Arrays.asList("NumPy"));
        extensionToLanguages.put("numsc", Arrays.asList("NumPy"));
        extensionToLanguages.put("mm", Arrays.asList("Objective-C++"));
        extensionToLanguages.put("objcpp", Arrays.asList("Objective-C++"));
        extensionToLanguages.put("mligo", Arrays.asList("OCaml"));
        extensionToLanguages.put("odin", Arrays.asList("Odin"));
        extensionToLanguages.put("opam", Arrays.asList("Opam"));
        extensionToLanguages.put("oz", Arrays.asList("Oz"));
        extensionToLanguages.put("p4", Arrays.asList("P4"));
        extensionToLanguages.put("pas", Arrays.asList("Pascal"));
        extensionToLanguages.put("p", Arrays.asList("Pascal"));
        extensionToLanguages.put("pp", Arrays.asList("Pascal", "Puppet"));
        extensionToLanguages.put("pl", Arrays.asList("Perl", "Prolog"));
        extensionToLanguages.put("pm", Arrays.asList("Perl"));
        extensionToLanguages.put("php", Arrays.asList("PHP"));
        extensionToLanguages.put("aw", Arrays.asList("PHP"));
        extensionToLanguages.put("ctp", Arrays.asList("PHP"));
        extensionToLanguages.put("php3", Arrays.asList("PHP"));
        extensionToLanguages.put("php4", Arrays.asList("PHP"));
        extensionToLanguages.put("php5", Arrays.asList("PHP"));
        extensionToLanguages.put("phps", Arrays.asList("PHP"));
        extensionToLanguages.put("phpt", Arrays.asList("PHP"));
        extensionToLanguages.put("phtml", Arrays.asList("PHP"));
        extensionToLanguages.put("pkl", Arrays.asList("Pkl"));
        extensionToLanguages.put("pklproj", Arrays.asList("Pkl"));
        extensionToLanguages.put("pls", Arrays.asList("PLSQL"));
        extensionToLanguages.put("plsql", Arrays.asList("PLSQL"));
        extensionToLanguages.put("pck", Arrays.asList("PLSQL"));
        extensionToLanguages.put("pkb", Arrays.asList("PLSQL"));
        extensionToLanguages.put("pks", Arrays.asList("PLSQL"));
        extensionToLanguages.put("sql", Arrays.asList("SQL", "PLSQL"));
        extensionToLanguages.put("pod", Arrays.asList("Pod"));
        extensionToLanguages.put("pogo", Arrays.asList("PogoScript"));
        extensionToLanguages.put("pony", Arrays.asList("Pony"));
        extensionToLanguages.put("postcss", Arrays.asList("PostCSS"));
        extensionToLanguages.put("pcss", Arrays.asList("PostCSS"));
        extensionToLanguages.put("ps", Arrays.asList("PostScript"));
        extensionToLanguages.put("eps", Arrays.asList("PostScript"));
        extensionToLanguages.put("pfa", Arrays.asList("PostScript"));
        extensionToLanguages.put("pov", Arrays.asList("POV-Ray SDL"));
        extensionToLanguages.put("praat", Arrays.asList("Praat"));
        extensionToLanguages.put("psc", Arrays.asList("Papyrus"));
        extensionToLanguages.put("ps1", Arrays.asList("PowerShell"));
        extensionToLanguages.put("psd1", Arrays.asList("PowerShell"));
        extensionToLanguages.put("psm1", Arrays.asList("PowerShell"));
        extensionToLanguages.put("prql", Arrays.asList("PRQL"));
        extensionToLanguages.put("pro", Arrays.asList("QMake"));
        extensionToLanguages.put("pri", Arrays.asList("QMake"));
        extensionToLanguages.put("proto", Arrays.asList("Protocol Buffer"));
        extensionToLanguages.put("pu", Arrays.asList("PlantUML"));
        extensionToLanguages.put("puml", Arrays.asList("PlantUML"));
        extensionToLanguages.put("plantuml", Arrays.asList("PlantUML"));
        extensionToLanguages.put("iuml", Arrays.asList("PlantUML"));
        extensionToLanguages.put("py", Arrays.asList("Python", "Snakemake"));
        extensionToLanguages.put("bzl", Arrays.asList("Starlark"));
        extensionToLanguages.put("ipynb", Arrays.asList("Jupyter Notebook"));
        extensionToLanguages.put("pyi", Arrays.asList("Python"));
        extensionToLanguages.put("rpy", Arrays.asList("Python"));
        extensionToLanguages.put("pyw", Arrays.asList("Python"));
        extensionToLanguages.put("sage", Arrays.asList("Python"));
        extensionToLanguages.put("tac", Arrays.asList("Python"));
        extensionToLanguages.put("wsgi", Arrays.asList("Python"));
        extensionToLanguages.put("xpy", Arrays.asList("Python"));
        extensionToLanguages.put("qmd", Arrays.asList("Quarto"));
        extensionToLanguages.put("q", Arrays.asList("q"));
        extensionToLanguages.put("r", Arrays.asList("R"));
        extensionToLanguages.put("rd", Arrays.asList("R"));
        extensionToLanguages.put("rsx", Arrays.asList("R"));
        extensionToLanguages.put("rkt", Arrays.asList("Racket"));
        extensionToLanguages.put("rktd", Arrays.asList("Racket"));
        extensionToLanguages.put("rktl", Arrays.asList("Racket"));
        extensionToLanguages.put("scrbl", Arrays.asList("Racket"));
        extensionToLanguages.put("raml", Arrays.asList("RAML"));
        extensionToLanguages.put("rbs", Arrays.asList("RBS"));
        extensionToLanguages.put("re", Arrays.asList("Reason"));
        extensionToLanguages.put("rei", Arrays.asList("Reason"));
        extensionToLanguages.put("reg", Arrays.asList("Windows Registry Entries"));
        extensionToLanguages.put("rego", Arrays.asList("Rego"));
        extensionToLanguages.put("rst", Arrays.asList("reStructuredText"));
        extensionToLanguages.put("rest", Arrays.asList("reStructuredText"));
        extensionToLanguages.put("rest.txt", Arrays.asList("reStructuredText"));
        extensionToLanguages.put("rst.txt", Arrays.asList("reStructuredText"));
        extensionToLanguages.put("rnh", Arrays.asList("RenderScript"));
        extensionToLanguages.put("rno", Arrays.asList("RenderScript"));
        extensionToLanguages.put("ring", Arrays.asList("Ring"));
        extensionToLanguages.put("rsc", Arrays.asList("RISC-V"));
        extensionToLanguages.put("robot", Arrays.asList("RobotFramework"));
        extensionToLanguages.put("rg", Arrays.asList("Rouge"));
        extensionToLanguages.put("rb", Arrays.asList("Ruby"));
        extensionToLanguages.put("builder", Arrays.asList("Ruby"));
        extensionToLanguages.put("eye", Arrays.asList("Ruby"));
        extensionToLanguages.put("gemspec", Arrays.asList("Ruby"));
        extensionToLanguages.put("god", Arrays.asList("Ruby"));
        extensionToLanguages.put("jbuilder", Arrays.asList("Ruby"));
        extensionToLanguages.put("mspec", Arrays.asList("Ruby"));
        extensionToLanguages.put("podspec", Arrays.asList("Ruby"));
        extensionToLanguages.put("rbi", Arrays.asList("Ruby"));
        extensionToLanguages.put("rbuild", Arrays.asList("Ruby"));
        extensionToLanguages.put("rbw", Arrays.asList("Ruby"));
        extensionToLanguages.put("rbx", Arrays.asList("Ruby"));
        extensionToLanguages.put("ru", Arrays.asList("Ruby"));
        extensionToLanguages.put("ruby", Arrays.asList("Ruby"));
        extensionToLanguages.put("spec", Arrays.asList("Ruby"));
        extensionToLanguages.put("thor", Arrays.asList("Ruby"));
        extensionToLanguages.put("watchr", Arrays.asList("Ruby"));
        extensionToLanguages.put("rs", Arrays.asList("Rust"));
        extensionToLanguages.put("sas", Arrays.asList("SAS"));
        extensionToLanguages.put("sass", Arrays.asList("Sass"));
        extensionToLanguages.put("sc", Arrays.asList("Scala", "SuperCollider"));
        extensionToLanguages.put("scala", Arrays.asList("Scala"));
        extensionToLanguages.put("sbt", Arrays.asList("Scala"));
        extensionToLanguages.put("scad", Arrays.asList("OpenSCAD"));
        extensionToLanguages.put("sce", Arrays.asList("Scilab"));
        extensionToLanguages.put("sci", Arrays.asList("Scilab"));
        extensionToLanguages.put("scss", Arrays.asList("SCSS"));
        extensionToLanguages.put("sh", Arrays.asList("Shell"));
        extensionToLanguages.put("bash", Arrays.asList("Shell"));
        extensionToLanguages.put("bsh", Arrays.asList("Shell"));
        extensionToLanguages.put("csh", Arrays.asList("Shell"));
        extensionToLanguages.put("ksh", Arrays.asList("Shell"));
        extensionToLanguages.put("tcsh", Arrays.asList("Shell"));
        extensionToLanguages.put("zsh", Arrays.asList("Shell"));
        extensionToLanguages.put("sh-session", Arrays.asList("ShellSession"));
        extensionToLanguages.put("sieve", Arrays.asList("Sieve"));
        extensionToLanguages.put("slim", Arrays.asList("Slim"));
        extensionToLanguages.put("smali", Arrays.asList("Smali"));
        extensionToLanguages.put("sml", Arrays.asList("Standard ML"));
        extensionToLanguages.put("fun", Arrays.asList("Standard ML"));
        extensionToLanguages.put("sig", Arrays.asList("Standard ML"));
        extensionToLanguages.put("smt", Arrays.asList("SMT"));
        extensionToLanguages.put("sol", Arrays.asList("Solidity"));
        extensionToLanguages.put("sfd", Arrays.asList("Spline Font Database"));
        extensionToLanguages.put("ss", Arrays.asList("Scheme"));
        extensionToLanguages.put("scm", Arrays.asList("Scheme"));
        extensionToLanguages.put("sp", Arrays.asList("SourcePawn"));
        extensionToLanguages.put("spl", Arrays.asList("Splunk SPL"));
        extensionToLanguages.put("sqf", Arrays.asList("SQF"));
        extensionToLanguages.put("st", Arrays.asList("Smalltalk"));
        extensionToLanguages.put("csq", Arrays.asList("Squirrel"));
        extensionToLanguages.put("cssq", Arrays.asList("Squirrel"));
        extensionToLanguages.put("nut", Arrays.asList("Squirrel"));
        extensionToLanguages.put("stan", Arrays.asList("Stan"));
        extensionToLanguages.put("do", Arrays.asList("Stata"));
        extensionToLanguages.put("ado", Arrays.asList("Stata"));
        extensionToLanguages.put("dta", Arrays.asList("Stata"));
        extensionToLanguages.put("mata", Arrays.asList("Stata"));
        extensionToLanguages.put("matah", Arrays.asList("Stata"));
        extensionToLanguages.put("sth", Arrays.asList("Stata"));
        extensionToLanguages.put("styl", Arrays.asList("Stylus"));
        extensionToLanguages.put("sugarss", Arrays.asList("SugarSS"));
        extensionToLanguages.put("sw", Arrays.asList("Strand"));
        extensionToLanguages.put("swift", Arrays.asList("Swift"));
        extensionToLanguages.put("sv", Arrays.asList("SystemVerilog"));
        extensionToLanguages.put("svh", Arrays.asList("SystemVerilog"));
        extensionToLanguages.put("vh", Arrays.asList("SystemVerilog"));
        extensionToLanguages.put("thrift", Arrays.asList("Thrift"));
        extensionToLanguages.put("tu", Arrays.asList("Turing"));
        extensionToLanguages.put("t", Arrays.asList("Terra", "Turing"));
        extensionToLanguages.put("ts", Arrays.asList("TypeScript", "XML"));
        extensionToLanguages.put("cts", Arrays.asList("TypeScript"));
        extensionToLanguages.put("mts", Arrays.asList("TypeScript"));
        extensionToLanguages.put("tsx", Arrays.asList("TypeScript"));
        extensionToLanguages.put("tcl", Arrays.asList("Tcl"));
        extensionToLanguages.put("itk", Arrays.asList("Tcl"));
        extensionToLanguages.put("tk", Arrays.asList("Tcl"));
        extensionToLanguages.put("tex", Arrays.asList("TeX"));
        extensionToLanguages.put("aux", Arrays.asList("TeX"));
        extensionToLanguages.put("cls", Arrays.asList("TeX", "Apex", "VBA", "Visual Basic 6.0"));
        extensionToLanguages.put("dtx", Arrays.asList("TeX"));
        extensionToLanguages.put("ins", Arrays.asList("TeX"));
        extensionToLanguages.put("ltex", Arrays.asList("TeX"));
        extensionToLanguages.put("sty", Arrays.asList("TeX"));
        extensionToLanguages.put("textile", Arrays.asList("Textile"));
        extensionToLanguages.put("tf", Arrays.asList("HCL"));
        extensionToLanguages.put("tfstate", Arrays.asList("HCL"));
        extensionToLanguages.put("tfvars", Arrays.asList("HCL"));
        extensionToLanguages.put("toml", Arrays.asList("TOML"));
        extensionToLanguages.put("tla", Arrays.asList("TLA"));
        extensionToLanguages.put("tsv", Arrays.asList("TSV"));
        extensionToLanguages.put("twig", Arrays.asList("Twig"));
        extensionToLanguages.put("uc", Arrays.asList("UnrealScript"));
        extensionToLanguages.put("vala", Arrays.asList("Vala"));
        extensionToLanguages.put("vapi", Arrays.asList("Vala"));
        extensionToLanguages.put("v", Arrays.asList("V", "Verilog", "Coq"));
        extensionToLanguages.put("vhdl", Arrays.asList("VHDL"));
        extensionToLanguages.put("vhd", Arrays.asList("VHDL"));
        extensionToLanguages.put("vho", Arrays.asList("VHDL"));
        extensionToLanguages.put("vhs", Arrays.asList("VHDL"));
        extensionToLanguages.put("vht", Arrays.asList("VHDL"));
        extensionToLanguages.put("vhw", Arrays.asList("VHDL"));
        extensionToLanguages.put("vim", Arrays.asList("Vim Script"));
        extensionToLanguages.put("vimrc", Arrays.asList("Vim Script"));
        extensionToLanguages.put("vmb", Arrays.asList("Vim Script"));
        extensionToLanguages.put("vb", Arrays.asList("VBA", "Visual Basic .NET"));
        extensionToLanguages.put("vba", Arrays.asList("VBA"));
        extensionToLanguages.put("vbs", Arrays.asList("VBScript"));
        extensionToLanguages.put("vcl", Arrays.asList("VCL"));
        extensionToLanguages.put("verilog", Arrays.asList("Verilog"));
        extensionToLanguages.put("veo", Arrays.asList("Verilog"));
        extensionToLanguages.put("volt", Arrays.asList("Volt"));
        extensionToLanguages.put("vue", Arrays.asList("Vue"));
        extensionToLanguages.put("wast", Arrays.asList("WebAssembly"));
        extensionToLanguages.put("wat", Arrays.asList("WebAssembly"));
        extensionToLanguages.put("whiley", Arrays.asList("Whiley"));
        extensionToLanguages.put("wlk", Arrays.asList("Wollok"));
        extensionToLanguages.put("x", Arrays.asList("Logos"));
        extensionToLanguages.put("xml", Arrays.asList("XML"));
        extensionToLanguages.put("adml", Arrays.asList("XML"));
        extensionToLanguages.put("admx", Arrays.asList("XML"));
        extensionToLanguages.put("ant", Arrays.asList("XML"));
        extensionToLanguages.put("axml", Arrays.asList("XML"));
        extensionToLanguages.put("builds", Arrays.asList("XML"));
        extensionToLanguages.put("ccproj", Arrays.asList("XML"));
        extensionToLanguages.put("ccxml", Arrays.asList("XML"));
        extensionToLanguages.put("clixml", Arrays.asList("XML"));
        extensionToLanguages.put("cproject", Arrays.asList("XML"));
        extensionToLanguages.put("csproj", Arrays.asList("XML"));
        extensionToLanguages.put("ct", Arrays.asList("XML"));
        extensionToLanguages.put("dita", Arrays.asList("XML"));
        extensionToLanguages.put("ditamap", Arrays.asList("XML"));
        extensionToLanguages.put("ditaval", Arrays.asList("XML"));
        extensionToLanguages.put("dll.config", Arrays.asList("XML"));
        extensionToLanguages.put("dotsettings", Arrays.asList("XML"));
        extensionToLanguages.put("filters", Arrays.asList("XML"));
        extensionToLanguages.put("fsproj", Arrays.asList("XML"));
        extensionToLanguages.put("fxml", Arrays.asList("XML"));
        extensionToLanguages.put("glade", Arrays.asList("XML"));
        extensionToLanguages.put("gml", Arrays.asList("XML"));
        extensionToLanguages.put("grxml", Arrays.asList("XML"));
        extensionToLanguages.put("iml", Arrays.asList("XML"));
        extensionToLanguages.put("ivy", Arrays.asList("XML"));
        extensionToLanguages.put("jelly", Arrays.asList("XML"));
        extensionToLanguages.put("jsproj", Arrays.asList("XML"));
        extensionToLanguages.put("kml", Arrays.asList("XML"));
        extensionToLanguages.put("launch", Arrays.asList("XML"));
        extensionToLanguages.put("mdpolicy", Arrays.asList("XML"));
        extensionToLanguages.put("mxml", Arrays.asList("XML"));
        extensionToLanguages.put("nproj", Arrays.asList("XML"));
        extensionToLanguages.put("nuspec", Arrays.asList("XML"));
        extensionToLanguages.put("odd", Arrays.asList("XML"));
        extensionToLanguages.put("osm", Arrays.asList("XML"));
        extensionToLanguages.put("pkgproj", Arrays.asList("XML"));
        extensionToLanguages.put("plist", Arrays.asList("XML"));
        extensionToLanguages.put("props", Arrays.asList("XML"));
        extensionToLanguages.put("ps1xml", Arrays.asList("XML"));
        extensionToLanguages.put("psc1", Arrays.asList("XML"));
        extensionToLanguages.put("pt", Arrays.asList("XML"));
        extensionToLanguages.put("publishsettings", Arrays.asList("XML"));
        extensionToLanguages.put("rdf", Arrays.asList("XML"));
        extensionToLanguages.put("rng", Arrays.asList("XML"));
        extensionToLanguages.put("rsd", Arrays.asList("XML"));
        extensionToLanguages.put("rss", Arrays.asList("XML"));
        extensionToLanguages.put("scxml", Arrays.asList("XML"));
        extensionToLanguages.put("srdf", Arrays.asList("XML"));
        extensionToLanguages.put("storyboard", Arrays.asList("XML"));
        extensionToLanguages.put("stTheme", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-build", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-commands", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-completions", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-keymap", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-macro", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-menu", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-project", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-settings", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-theme", Arrays.asList("XML"));
        extensionToLanguages.put("sublime-workspace", Arrays.asList("XML"));
        extensionToLanguages.put("sublime_metrics", Arrays.asList("XML"));
        extensionToLanguages.put("sublime_session", Arrays.asList("XML"));
        extensionToLanguages.put("svc", Arrays.asList("XML"));
        extensionToLanguages.put("targets", Arrays.asList("XML"));
        extensionToLanguages.put("tmCommand", Arrays.asList("XML"));
        extensionToLanguages.put("tmLanguage", Arrays.asList("XML"));
        extensionToLanguages.put("tmPreferences", Arrays.asList("XML"));
        extensionToLanguages.put("tmSnippet", Arrays.asList("XML"));
        extensionToLanguages.put("tmTheme", Arrays.asList("XML"));
        extensionToLanguages.put("ui", Arrays.asList("XML"));
        extensionToLanguages.put("urdf", Arrays.asList("XML"));
        extensionToLanguages.put("ux", Arrays.asList("XML"));
        extensionToLanguages.put("vbproj", Arrays.asList("XML"));
        extensionToLanguages.put("vcxproj", Arrays.asList("XML"));
        extensionToLanguages.put("vdx", Arrays.asList("XML"));
        extensionToLanguages.put("vsixmanifest", Arrays.asList("XML"));
        extensionToLanguages.put("vssettings", Arrays.asList("XML"));
        extensionToLanguages.put("vxml", Arrays.asList("XML"));
        extensionToLanguages.put("wsdl", Arrays.asList("XML"));
        extensionToLanguages.put("wxi", Arrays.asList("XML"));
        extensionToLanguages.put("wxl", Arrays.asList("XML"));
        extensionToLanguages.put("wxs", Arrays.asList("XML"));
        extensionToLanguages.put("x3d", Arrays.asList("XML"));
        extensionToLanguages.put("xacro", Arrays.asList("XML"));
        extensionToLanguages.put("xaml", Arrays.asList("XML"));
        extensionToLanguages.put("xib", Arrays.asList("XML"));
        extensionToLanguages.put("xlf", Arrays.asList("XML"));
        extensionToLanguages.put("xliff", Arrays.asList("XML"));
        extensionToLanguages.put("xmi", Arrays.asList("XML"));
        extensionToLanguages.put("xml.dist", Arrays.asList("XML"));
        extensionToLanguages.put("xmp", Arrays.asList("XML"));
        extensionToLanguages.put("xproj", Arrays.asList("XML"));
        extensionToLanguages.put("xsd", Arrays.asList("XML"));
        extensionToLanguages.put("xspec", Arrays.asList("XML"));
        extensionToLanguages.put("xul", Arrays.asList("XML"));
        extensionToLanguages.put("zcml", Arrays.asList("XML"));
        extensionToLanguages.put("x", Arrays.asList("Logos"));
        extensionToLanguages.put("xq", Arrays.asList("XQuery"));
        extensionToLanguages.put("xql", Arrays.asList("XQuery"));
        extensionToLanguages.put("xqm", Arrays.asList("XQuery"));
        extensionToLanguages.put("xqy", Arrays.asList("XQuery"));
        extensionToLanguages.put("xquery", Arrays.asList("XQuery"));
        extensionToLanguages.put("xs", Arrays.asList("XS"));
        extensionToLanguages.put("xslt", Arrays.asList("XSLT"));
        extensionToLanguages.put("xsl", Arrays.asList("XSLT"));
        extensionToLanguages.put("yaml", Arrays.asList("YAML"));
        extensionToLanguages.put("yml", Arrays.asList("YAML"));
        extensionToLanguages.put("reek", Arrays.asList("YAML"));
        extensionToLanguages.put("rviz", Arrays.asList("YAML"));
        extensionToLanguages.put("sublime_syntax", Arrays.asList("YAML"));
        extensionToLanguages.put("syntax", Arrays.asList("YAML"));
        extensionToLanguages.put("yaml-tmlanguage", Arrays.asList("YAML"));
        extensionToLanguages.put("yaml.sed", Arrays.asList("YAML"));
        extensionToLanguages.put("yml.dist", Arrays.asList("YAML"));
        extensionToLanguages.put("y", Arrays.asList("Yacc"));
        extensionToLanguages.put("yacc", Arrays.asList("Yacc"));
        extensionToLanguages.put("yy", Arrays.asList("Yacc"));
        extensionToLanguages.put("zap", Arrays.asList("ZAP"));
        extensionToLanguages.put("zig", Arrays.asList("Zig"));
        extensionToLanguages.put("zir", Arrays.asList("Zig"));
        extensionToLanguages.put("zsh", Arrays.asList("Shell"));
    }

}